name: WTFSurvival
version: ${project.version}
main: top.jingwenmc.wtfsurvival.WTFSurvival
api-version: 1.16
authors: [ jingwenMC ]
description: A Funny Survival Minigame Framework
website: www.jingwenmc.top
commands:
  wtfs:
    description: Main Command
    aliases: [wtfsurvival,wtfsc]
    usage: /wtfs help
permissions:
  wtfs.login:
    default: op